name: Feature branches

on:
  push:
    branches:    
      - '**'
      - '!master'

env:
  GITHUB_REPO_USERNAME: ${{ secrets.GH_MAVEN_USER }}
  GITHUB_REPO_PASSWORD: ${{ secrets.GH_MAVEN_PASSWORD }}

jobs:
  formatting:
    name: Check code formatting
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v1
      - name: Cache Maven dependencies
        uses: actions/cache@v2
        env:
          cache-name: cache-maven-dependencies
        with:
          path: ~/.m2
          key: ${{ runner.os }}-codeformat-${{ env.cache-name }}-${{ hashFiles('pom.xml') }}
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.4
      - name: Run Spotless Check
        run: mvn -B clean spotless:check --settings .github/settings.xml

  spotbugs:
    name: Check for bugs
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v1
      - name: Cache Maven dependencies
        uses: actions/cache@v2
        env:
          cache-name: cache-maven-dependencies
        with:
          path: ~/.m2
          key: ${{ runner.os }}-spotbugs-${{ env.cache-name }}-${{ hashFiles('pom.xml') }}
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.4
      - name: Run SpotBugs Check
        run: mvn apt:process -B verify -DskipTests -DskipITs --settings .github/settings.xml
      - if: failure()
        run: mvn -B site --settings .github/settings.xml
      - if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: Spotbugs report
          path: target/site/*

  test:
    name: Run unit & integration tests
    runs-on: ubuntu-20.04
    needs: [formatting, spotbugs]

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: aVeryHardPasswordToGuess
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v1
      - name: Setup database
        run: |
          sudo apt-get update
          sudo apt-get install postgresql-12
          psql postgresql://postgres@localhost/postgres < .docker/setup-postgres.sql
        env:
          PGPASSWORD: aVeryHardPasswordToGuess
      - name: Cache Maven dependencies
        uses: actions/cache@v2
        env:
          cache-name: cache-maven-dependencies
        with:
          path: ~/.m2
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('pom.xml') }}
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.4
      - name: Maven Package
        run: mvn -B clean package -DskipTests -Dspotbugs.skip=true --settings .github/settings.xml
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v2.6.0
        env:
          # Set CC_TEST_REPORTER_ID as secret of your repo
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
          JACOCO_SOURCE_PATH: "${{github.workspace}}/src/main/java"
        with:
          # The report file must be there, otherwise Code Climate won't find it
          coverageCommand: mvn -B clean verify -Dspotbugs.skip=true --settings .github/settings.xml
          coverageLocations: ${{github.workspace}}/target/site/jacoco/jacoco.xml:jacoco
